### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by sboeuf**
### Summary of the PR

This release includes:
- Fix vring initialization logic
- Bump to virtio-queue v0.5.0

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Review by stefano-garzarella — DISMISSED** [review]

**Review by slp — CHANGES_REQUESTED** [review]
As https://github.com/rust-vmm/vhost-user-backend/pull/78 introduced breaking changes into the API, according to SemVer this needs to be `v0.6.0` instead of `v0.5.2`.

**Comment by sboeuf** [comment]
> As #78 introduced breaking changes into the API, according to SemVer this needs to be `v0.6.0` instead of `v0.5.2`.

Well at first I thought #78 introduced breaking changes but looking at it, I don't think it actually did. I mean the breaking change comes from the fact that it relies on `virtio-queue` 0.5.0 which introduced breaking changes. I'm more than happy to update this PR to release 0.6.0, just want to make sure we do the right thing.

**Comment by sboeuf** [comment]
I guess the fact that the consumer of `vhost-user-backend` will have to update its code (even if it's caused by virtio-queue), meaning this is a breaking change that can't be considered a patch but rather a minor version update.

**Comment by sboeuf** [comment]
PR updated! @stefano-garzarella @slp

**Review by stefano-garzarella — APPROVED** [review]

**Review by rbradford — APPROVED** [review]

**Pull request merged**
