### PR TITLE
Various vring fixes

### PR DESCRIPTION
**Pull request by slp**
This PR includes two important fixes, and two minor style and functional improvements.

The important ones fix a behavior issue that may lead to the vhost-user device to miss signalling a completion event to the Guest, and the fact the we weren't resetting the underlying Queue at any time.

### CODE REVIEW

**Review by sboeuf — APPROVED** [review]
Looks good. Have you tested this properly?

**Comment by slp** [comment]
@sboeuf These changes should only have an impact on vring initialization, so I tested boot and reboot (in addition to device functionality) with virtiofsd-rs and the new [vhost-device/scsi](https://github.com/Gaelan/vhost-device/tree/scsi/src/scsi) as devices, and QEMU as VMM (I should probably add another VMM to my dev environment 🤔)

**Comment by slp** [comment]
@jiangliu @sboeuf PTAL

**Review by sboeuf — DISMISSED** [review]

**Review by stefano-garzarella — APPROVED** [review]

**Comment by jiangliu** [comment]
Could you please help to rebase the MR?

**Comment by slp** [comment]
> Could you please help to rebase the MR?

Done. :-)

**Review by jiangliu — APPROVED** [review]

**Pull request merged**
