### PR TITLE
backend: Set remote dependency branch as main

### PR DESCRIPTION
**Pull request by vireshk**
The builds are failing since the the remote branch's name is changed to
main from master. Fix it.

Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
@vireshk can you sign your commit?

**Comment by vireshk** [comment]
> @vireshk can you sign your commit?

Did that, I created this pull request using the web interface (my first) and so the mess :(

**Comment by andreeaflorescu** [comment]
The web interface is not adding the signed-off-by, that's why I don't use it.

**Comment by vireshk** [comment]
@andreeaflorescu the builkd isn't starting again, how do I trigger it ?

**Comment by slp** [comment]
While the `master` branch has been renamed to `main`, the latter has been made the default one. Do we really need to explicitly reference `main`? Which error are you getting?

**Comment by vireshk** [comment]
> While the `master` branch has been renamed to `main`, the latter has been made the default one. Do we really need to explicitly reference `main`? Which error are you getting?

https://buildkite.com/rust-vmm/vhost-user-backend-ci/builds/60#0e2f7b7b-b1b3-41fa-9244-6c75223742de

**Comment by slp** [comment]
> > While the `master` branch has been renamed to `main`, the latter has been made the default one. Do we really need to explicitly reference `main`? Which error are you getting?
> 
> https://buildkite.com/rust-vmm/vhost-user-backend-ci/builds/60#0e2f7b7b-b1b3-41fa-9244-6c75223742de

This should have been fixed by https://github.com/rust-lang/cargo/pull/9133

Is our CI using an older version?

**Comment by vireshk** [comment]
I will let @andreeaflorescu take over this discussion now :)

**Comment by andreeaflorescu** [comment]
I guess it depends on the `cargo` version that you are using. In what version was that fixed?

Locally, for me it fails with:
```

**Comment by slp** [comment]
> I guess it depends on the `cargo` version that you are using. In what version was that fixed?

I'm running the latest stable version:

```
$ cargo --version
cargo 1.54.0 (5ae8d74b3 2021-06-22)
```

> Using HEAD is not a good option because the builds will fail with any incompatible change in the consuming crates. An explicit commit I think is the preferred way.

I'd certainly prefer fixing this with a `rev = "6013dd9"` than with a `branch = "main"`.

**Comment by vireshk** [comment]
> I'd certainly prefer fixing this with a `rev = "6013dd9"` than with a `branch = "main"`.

But that will bind this to an older version (in future), why should we do that ?

**Comment by andreeaflorescu** [comment]
> > I'd certainly prefer fixing this with a `rev = "6013dd9"` than with a `branch = "main"`.
> 
> But that will bind this to an older version (in future), why should we do that ?

The idea is to fix the revision, and then update the dependabot configuration such that it provides the updates to the revision. This comes with the advantage that the main branch always builds, and you are not lagging behind because dependabot will open PRs to update the revision whenever a new commit is added to vm-virtio for example.

If you look at the current dependabot configuration, it does updates for git: https://github.com/rust-vmm/vhost-user-backend/blob/5dde7f196b071bd97cbe2dc78d94ff11b8b9fa77/.github/dependabot.yml#L3 (the package ecosystem is submodule). This means that it updates only the rust-vmm-ci.

This can be setup to also update crate dependencies, by specifying as ecosystem `cargo`. You can check the cloud hypervisor configuration for an example: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/6c142e35f787aad2ac91f24e2379d5b1c685d599/.github/dependabot.yml#L3

With dependabot, it will be easy to always use the latest available option as long as the build still passes. IF the build fails, then manual updates will be needed, but this is expected to happen when you do not want to break the main branch.

**Comment by slp** [comment]
> > I'd certainly prefer fixing this with a `rev = "6013dd9"` than with a `branch = "main"`.
> 
> But that will bind this to an older version (in future), why should we do that ?

Because, until it's published on [crates.io](https://crates.io), `vm-virtio` is allowed to introduce breaking changes in its API. This means we can't guarantee that we will support any future version without changes in `vhost-user-backend` itself.

In other words, referring to particular shields us against getting broken by changes in `vm-virtio`. Of course that means we'll need to periodically check manually if we should update the commit reference to incorporate new feature/fixes but, in practice, that's something we'll also need to do once `vm-virtio` gets published, so we might as well get used to that now.

**Comment by vireshk** [comment]
I keep forgetting that dependabot have magical powers. Fixed it with rev now.

**Comment by slp** [comment]
@vireshk Thanks!

@jiangliu If we merge this, you'll need to drop your last commit in #30 . Are you OK with that?

**Review by andreeaflorescu — APPROVED** [review]

**Review by jiangliu — APPROVED** [review]

**Pull request merged**
